repos:
- repo: https://github.com/ambv/black
  rev: 21.9b0
  hooks:
  - id: black
    language_version: python3.8

- repo: local
  hooks:
  - id: pylint
    name: pylint
    language: system
    types: [python]
    entry: bash -c "python lint.py -p ../generatore-interattivo/"
