version: "3"

services:

  generatore_interattivo_django:
    container_name: generatore_interattivo_django
    restart: always
    build: .
    depends_on:
      - generatore_db
    volumes:
      - ../:/app
    command: "/bin/bash /app/docker/worker/entrypoint.sh"
    links:
      - "generatore_db"
    env_file: "prod/envs/generatore_interattivo_django.env"
    deploy:
      resources:
        limits:
          cpus: '0.90'
          memory: 12288M  # 12gb
        reservations:
          cpus: '0.10'
          memory: 100M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.generatoreinterattivo.entrypoints=websecure"
      - "traefik.http.services.generatoreinterattivo.loadbalancer.server.port=80"
      - "traefik.http.routers.generatoreinterattivo.rule=Host(`pdf2jpg.interattivo.net`)"
      - "traefik.http.routers.generatoreinterattivo.tls.certresolver=lets-encr"

  generatore_db:
    container_name: generatore_db
    restart: always
    env_file: "prod/envs/generatore_db.env"
    image: mysql:5.7
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    volumes:
      - ./worker/mysql-data:/var/lib/mysql

networks:
  default:
    external:
      name: traefik_net
