version: "3"

services:

  generatore_interattivo_django:
    container_name: generatore_interattivo_django
    build: .
    volumes:
      - ../:/app
    command: "/bin/bash /app/docker/prod/entrypoint.sh"
    env_file: "prod/envs/generatore_interattivo_django.env"
    deploy:
      resources:
        limits:
          cpus: '0.90'
          memory: 12288M  # 12gb
        reservations:
          cpus: '0.10'
          memory: 100M

  generatoreint_nginx:
    container_name: generatoreint_nginx
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ../static:/app/static
      - ../media:/app/media
      - ./prod/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - generatore_interattivo_django
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.generatoreinterattivo.entrypoints=websecure"
      - "traefik.http.services.generatoreinterattivo.loadbalancer.server.port=80"
      - "traefik.http.routers.generatoreinterattivo.rule=Host(`dev02.interattivo.net`)"
      - "traefik.http.routers.generatoreinterattivo.tls.certresolver=lets-encr"

networks:
  default:
    external:
      name: traefik_net
