version: "3"

services:

  generatore_interattivo_django:
    container_name: generatore_interattivo_django
    restart: always
    build: .
    volumes:
      - ../:/app
    command: "/bin/bash /app/docker/dev/entrypoint.sh"
    env_file: "prod/envs/generatore_interattivo_django_debug.env"
    deploy:
      resources:
        limits:
          cpus: '0.90'
          memory: 12288M  # 12gb
        reservations:
          cpus: '0.10'
          memory: 100M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.generatoreinterattivo.entrypoints=websecure"
      - "traefik.http.services.generatoreinterattivo.loadbalancer.server.port=80"
      - "traefik.http.routers.generatoreinterattivo.rule=Host(`inpublish.interattivo.net`)"
      - "traefik.http.routers.generatoreinterattivo.tls.certresolver=lets-encr"

networks:
  default:
    external:
      name: traefik_net
